### PR TITLE
Separate permission for downloading files

### PR DESCRIPTION
**Pull request by UUBlueFire**
I require a separate permission for downloading files from the panel. I have implemented and tested this on my own panel.

### CODE REVIEW

**Comment by DaneEveritt** [comment]
How is this any different than the read content one?

**Comment by UUBlueFire** [comment]
I would like it to be so that people can view the contents of a file but not download the file

**Comment by DaneEveritt** [comment]
There is literally no difference is what I'm saying. If they want to download the file it is trivial for them to do so if they can already view the contents, and absolutely nothing would stop them with SFTP access. In fact, this permission only makes it more confusing for things like SFTP which is why the permissions are laid out how they are.

Appreciate the idea, but it doesn't really work well with how everything else is setup permissions wise.

**Comment by diamkil** [comment]
@DaneEveritt Yeah but people add users to configure plugins but don't want them downloading the paid plugins, maybe the download perm should be on the SFTP permission instead of read-contents

**Pull request closed without merging**
