### PR TITLE
Fixed TooManyLoginAttempts not work correctly

### PR DESCRIPTION
**Pull request by zKoz210**
We use username(), so the cache key will be created correctly

image

Variables have also changed:
image

### CODE REVIEW

**Comment by zKoz210** [comment]
@DaneEveritt It's about security, I think it's important.

**Comment by DaneEveritt** [comment]
Yes, but it isn't actually causing a security issue, its just using Laravel's (sane) defaults right now rather than our higher ones. I'll review this when I have time, but it isn't urgent.

**Comment by zKoz210** [comment]
It doesn't work at all because username cannot be obtained.

**Comment by DaneEveritt** [comment]
You'll get a null value, thus making the key `|<ip>` which will still work, albeit locking all users and not just a single one on that IP address.

**Comment by lancepioch** [comment]
* Why did you switch the constant to a function?
* Not sure if it's safe for an unsanitized string to make up the key in the cache
* Why change the lockout time from 120 to 2?

**Comment by zKoz210** [comment]
1) Because the function takes data from username()
2) default by Laravel 
3) Now time in minute, not seconds

**Comment by lancepioch** [comment]
This looks good to me after reviewing the traits. Magic and Laravel together

https://github.com/laravel/framework/blob/54bff8bd156c7817d5f32a4696474c72a2154f45/src/Illuminate/Foundation/Auth/ThrottlesLogins.php#L23-L25
https://github.com/laravel/framework/blob/3500e77d6ae85953e0b94b78530239a45231cc61/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php#L94

**Pull request merged**
