### PR TITLE
Update jQuery to 3.5.0

### PR DESCRIPTION
**Pull request by LeCodeCo**
Will fix these:
- https://app.snyk.io/vuln/SNYK-JS-JQUERY-174006
- https://app.snyk.io/vuln/SNYK-JS-JQUERY-565129

### CODE REVIEW

**Comment by LeCodeCo** [comment]
Not sure if the frontend JS breaks on this update. It _shouldn't_, but it's possible.

**Comment by lancepioch** [comment]
I'm pretty sure jQuery isn't used anywhere, these dangling references should be removed, feel free to PR that, thanks

**Comment by schrej** [comment]
> I'm pretty sure jQuery isn't used anywhere

Yes, it is.
https://github.com/pterodactyl/panel/tree/develop/public/themes/pterodactyl/js/admin

**Comment by DaneEveritt** [comment]
@schrej I don't think that is using jQuery from node_modules though.

**Comment by lancepioch** [comment]
Those files either only use basic jquery selectors/functions or they use select2 which can be replaced with something like https://react.semantic-ui.com/modules/dropdown/#types-multiple-selection.

**Comment by schrej** [comment]
Well, ideally we'll just rewrite the admin part in React as well 😄

**Comment by lancepioch** [comment]
Closing because we'll be removing all jquery. I'll learn React if that's what it takes to kill the beast once and for all.

**Pull request closed without merging**
