### PR TITLE
Add OAuth support

### PR DESCRIPTION
**Pull request by jer3m01**
## OAuth Sign In Support
Allows users to connect using external services through OAuth.

Out of the box this will support Discord, Google, GitHub, Twitter,
GitLab, BitBucket, LinkedIn and Facebook.

This is a follow-up of #1488.

~~Still in progress.~~

### CODE REVIEW

**Comment by FoksVHox** [comment]
This seems like a great idea :)

**Comment by jer3m01** [comment]
Preview of the admin settings page.

Admin Settings Page

**Comment by matthewpi** [comment]
You might want to check the `config/pterodactyl.php`, you are using `env('APP_OAUTH_DISCORD_REDIRECT_URI')` as the `redirect` for all of the providers, if this is intended (for all of them to redirect to a single place) then it should probably be renamed to `APP_OAUTH_REDIRECT_URI`.

**Comment by FoksVHox** [comment]
I feel like the admin page for the OAuths is a bit doll or old looking. Maybe I could look good if every OAuth had its own box?
image
I know that there isn't that many OAuth out of the box, as there is boxes on the picture.

**Comment by jer3m01** [comment]
> 
> 
> You might want to check the `config/pterodactyl.php`, you are using `env('APP_OAUTH_DISCORD_REDIRECT_URI')` as the `redirect` for all of the providers, if this is intended (for all of them to redirect to a single place) then it should probably be renamed to `APP_OAUTH_REDIRECT_URI`.

The route has been hardcoded, that was only used as a placeholder.  [controller](https://github.com/pterodactyl/panel/pull/1964/commits/278e41f13fb2b6abb586c7d36e9946306358d85a#diff-bb8abdff3cb7271df6c9de4b887de7bdR60) [route](https://github.com/pterodactyl/panel/pull/1964/commits/278e41f13fb2b6abb586c7d36e9946306358d85a#diff-ca728f4afab8b825e2ca36d8c2bf737bR33)



> 
> 
> I feel like the admin page for the OAuths is a bit doll or old looking. Maybe I could look good if every OAuth had its own box?
> image
> I know that there isn't that many OAuth out of the box, as there is boxes on the picture.

Going to leave it as it is since the admin UI will get recoded in React.
But you would still only view this page one time when you set it up 
so I don't really see a need for a fancy interface.

**Comment by jer3m01** [comment]
Preview of the login page.

Login page

**Comment by ocanty** [comment]
Would it be possible to have a 'custom' oauth driver? i.e one that supports generic endpoints.

Letting it interface with stuff like Keycloak comes to mind, would be v. helpful
I would be willing to test this for you if possible

**Comment by jer3m01** [comment]
> 
> 
> Would it be possible to have a 'custom' oauth driver? i.e one that supports generic providers rather than the social media ones outlined above
> 
> Letting it interface with stuff like Keycloak comes to mind, would be v. helpful
> I would be willing to test this for you if possible

Of course, custom drivers are planned.
This relies on [Laravel Socialite](https://laravel.com/docs/master/socialite) & [Socialite Providers](https://socialiteproviders.netlify.app/).

More specifically a [socialite provider for Keycloak](https://socialiteproviders.netlify.app/providers/keycloak.html) already exists.
In depth configuration will be provided later on in the pterodactyl docs.

**Comment by jer3m01** [comment]
Preview of the account OAuth linking page.

OAuth linking page

**Comment by DaneEveritt** [comment]
I think Google & Discord are plenty, perhaps Github/Gitlab as well. Linkedin/Facebook/BitBucket/Twitter are not going to be very frequent. I'm a fan of the oauth support, but not a huge fan of having every provider under the sun be shipped.

Especially because of the inevitable flood of "why isn't this working" that will come with this feature.

**Comment by schrej** [comment]
Imo there should be a "custom" option as well, then people can just add their own providers as well.

**Comment by FoksVHox** [comment]
> Imo there should be a "custom" option as well, then people can just add the providers they need, e.g. their own.

I agree, I’m currently working on a SSO for a hosting service, who uses Pterodactyl as the their game panel, if this comes before I’m done with the SSO it would be very helpful since I don’t need to work as hard as I otherwise should.

**Comment by jer3m01** [comment]
> 
> 
> I think Google & Discord are plenty, perhaps Github/Gitlab as well. Linkedin/Facebook/BitBucket/Twitter are not going to be very frequent. I'm a fan of the oauth support, but not a huge fan of having every provider under the sun be shipped.
> 
> Especially because of the inevitable flood of "why isn't this working" that will come with this feature.

I get what you mean but except discord those ship with Laravel Socialite [listed here](https://laravel.com/docs/master/socialite#introduction).


> 
> 
> Imo there should be a "custom" option as well, then people can just add the providers they need, e.g. their own.


> 
> 
> I agree, I’m currently working on a SSO for a hosting service, who uses Pterodactyl as the their game panel, if this comes before I’m done with the SSO it would be very helpful since I don’t need to work as hard as I otherwise should.

Sure I'll provide a generic driver with endpoint options in the config.

**Comment by FoksVHox** [comment]
Any news on this @jer3m01?

**Comment by jer3m01** [comment]
Has been a while, I'll get back on this.

**Comment by jer3m01** [comment]
Preview of the driver creation
OAuth settings creation modal
OAuth settings

**Comment by FoksVHox** [comment]
Please capitalize the name of the drivers, it triggering my OCD

**Comment by jer3m01** [comment]
> 
> 
> Please capitalize the name of the drivers, it triggering my OCD, but else does it look very sick!

Thanks!
The name of the drivers are case sensitive, can't capitalize them.

**Comment by FoksVHox** [comment]
> Thanks!
> The name of the drivers are case sensitive, can't capitalize them.

Just do `{{ Str::ucfirst($driver) }}`?

**Comment by jer3m01** [comment]
> 
> Just do `{{ Str::ucfirst($driver) }}`?

Yes it is possible but I would rather see the name as is rather than have the 
hassle of my driver (user added) not working because when added it's name
wasn't correctly capitalized.

**Comment by jer3m01** [comment]
Preview of the generic driver.
OAuth settings
Generic Driver options
Located at `pterodactyl.auth.oauth.generic`

**Review by Bencor29 — CHANGES_REQUESTED** [review]
Hi,

I don't understand why you try to get the user from a discord URL for the generic driver.
Is it an error ?

[https://github.com/pterodactyl/panel/pull/1964/files#diff-f4e0aea31a5a10cfbbdd5963a0435fa3R65-R77](https://github.com/pterodactyl/panel/pull/1964/files#diff-f4e0aea31a5a10cfbbdd5963a0435fa3R65-R77)

**Comment by jer3m01** [comment]
> 
> I don't understand why you try to get the user from a discord URL for the generic driver.
> Is it an error ?

Yes that is a mistake, thanks for the catch.

**Comment by zelkoa** [comment]
Hello i cant use artisan migrate 
image

**Review by fadedmax — DISMISSED** [review]
not a official reviewer, but the code looks good to me :)

**Comment by ocanty** [comment]
@jer3m01 would it be possible to add ENV variables that allow you to change the generic driver URIs without the need to modify the PHP file?

image

**Comment by Wunderharke** [comment]
How is it going with this feature? Could this be merged before the release of v1.0.0?

**Comment by DaneEveritt** [comment]
It will not be merged before 1.0 is released, we're under a feature freeze until that time.

**Comment by fadedmax** [comment]
Do we have any update on this? All the code looks good too me and it seems like we might want to start beta testing

**Comment by ghost** [comment]
Yeah is there any further advancement as I truly believe that this is a great feature that would make a lot of peoples lives easier

**Review by grzegorzkibitz — DISMISSED** [review]
Looks good with me, cant wait once features start getting added

**Comment by Jarvvski** [comment]
Also looking forward to seeing this release

**Comment by schrej** [comment]
Please only comment when you can actually contribute something meaningful to the PR. Anything in the direction of "when will this be added" or "this would be a great addition" is considered as +1 and therefore spam. Thanks.

**Comment by Jarvvski** [comment]
> Please only comment when you can actually contribute something meaningful to the PR. Anything in the direction of "when will this be added" or "this would be a great addition" is considered as +1 and therefore spam. Thanks.

More than happy to contribute! I don't see what else the maintainers want here - if you're willing to tell me what you need to unblock this, then I'll open this up in my editor right then and there.

I think it's a bit much to call this spam, when people are clearly showing a need for it. 

You've said you're in a feature freeze until 1.0, but that's come and gone. What's the hold up?

**Comment by schrej** [comment]
The main "holdup" is time I would say. After a release, especially a large one, the focus is usually fixing any bugs that come up, and there have been a few of those. As this is a pretty big feature that's additionally related to security, reviewing it will take quite a lot of time.

It's not blocked anymore, it's just not reviewed yet.
An easy way to contribute with this would be to thoroughly test it and summarize your method and results here.

**Comment by lusu007** [comment]
Is there any news on this yet? I think that a lot of users are eagerly waiting for OAuth. 😄

**Comment by FaustinM** [comment]
That's a cool feature :tada:

**Comment by Dream-cake** [comment]
yeah!

**Review by DitIsVincentPM — DISMISSED** [review]
Seems good

**Comment by Gaeta** [comment]
Have we thought about adding whmcs support native like discord etc before adding this fully?

**Comment by ririko5834** [comment]
Please add this soon

**Comment by trentnbauer** [comment]
Super keen to see this implemented!

**Comment by PenguinNexus** [comment]
I would like to add into this request an ability to set that only users with certain roles are permitted to login (for the Discord OAuth2 login route). That way, it prevents just anyone with a Discord account being able to log in, and then allows it so that only those with that particular role such as a "Panel Login" role access to the system.

**Comment by zaourzag** [comment]
i have just tested this with the latsest version of ptero and it works it was a hassle tho. had to manually build the assets (npm run buld:production) bit its super good

**Comment by FoksVHox** [comment]
> i have just tested this with the latsest version of ptero and it works it was a hassle tho. had to manually build the assets (npm run buld:production) bit its super good

That would change when and if the PR gets merged.

**Comment by zaourzag** [comment]
> > i have just tested this with the latsest version of ptero and it works it was a hassle tho. had to manually build the assets (npm run buld:production) bit its super good
> 
> That would change when and if the PR gets merged.

i know that but i want to help others trying this

**Review by Bencor29 — DISMISSED** [review]
I'm not an official reviewer, but that's looks good to me

**Review by JWaldecker — DISMISSED** [review]
I'm also not an official reviewer but for me the changes look good and I would appreciate merging them

**Comment by matthewpi** [comment]
Unless you are a member of the project team, your review won't do anything and will not speed up this PR.  All it will do is trigger a useless notification for anyone watching the repository and add spam to the comments.  Also, if you haven't noticed already, there are merge conflicts on this PR most likely caused by the upgrade to Laravel 8 which this PR was not tested on by the creator, meaning this will (and cannot) be merged until that is resolved.

**Review by adrijanb — DISMISSED** [review]
Looks good

**Comment by Torbikini** [comment]
This looks pretty good, nice work. Only thing I’m curious about is do people have to still create a normal pterodactyl account and then associate a social provider or are you just checking by matching email addresses? (Matching by email addresses is fine ***if and only if*** you know that the OAuth provider has verified the email. I know some differentiate between an email and verified email.)

I’m curious to see how this is going to play out and major kudos to you for taking on such a daunting task! I can’t wait to get OAuth support added to my panel down the road!

**Comment by nicolas-janzen** [comment]
I would appreciate merging to

**Review by felixklauke — DISMISSED** [review]

**Review by nicolas-janzen — DISMISSED** [review]

**Review by FlorianGH — DISMISSED** [review]

**Review by c-sakel — DISMISSED** [review]

**Comment by DaneEveritt** [comment]
To everyone constantly spamming comments on here and giving your "approved" reviews: please understand it is _incredibly_ annoying and spams all of us with notifications. Your reviews do not make me go "yeah I'm just going to click merge" on this.

Your spam has made me even less likely to be motivated enough to look at this because it is constantly low-value contributions and discussions. As a result we've locked this discussion.

**Comment by schrej** [comment]
Closing this since the fork got removed. See #3774 for an updated PR.

@jer3m01 thanks for opening this PR and sorry that we didn't find the time to review and merge this. Sometimes it's difficult. I hope that the new one will get merged instead, which still contains your work, so it's hopefully not lost.

**Pull request closed without merging**
