### PR TITLE
Update egg-teamspeak3-server.json

### PR DESCRIPTION
**Pull request by robingroppe**
- Change to official Teamspeak repo 
- Change to alpine specific tarballs
- Update to latest Teamspeak Server version

### CODE REVIEW

**Comment by parkervcp** [comment]
Also seeing as they now have a server.json file that will tell you what releases are out.

```
apk add --no-cache tar curl jq

if [ -z ${TS_VERSION} ] || [ ${TS_VERSION} == latest ]; then
    TS_VERSION=$(wget https://teamspeak.com/versions/server.json -qO - | jq -r '.linux.x86_64.version')
fi

cd /mnt/server


echo -e "getting files from http://files.teamspeak-services.com/releases/server/${TS_VERSION}/teamspeak3-server_linux_amd64-${TS_VERSION}.tar.bz2"
curl http://files.teamspeak-services.com/releases/server/${TS_VERSION}/teamspeak3-server_linux_amd64-${TS_VERSION}.tar.bz2 | tar xj --strip-components=1
```

**Comment by robingroppe** [comment]
I have to say that I don't like the approach to switch to a image with a larger footprint instead of grabbing the correct binary.
The alpine build is there for a reason... ;P

Nice to know there ist a version grabber, i was about to so the same this evening

**Comment by parkervcp** [comment]
I have updated the image not knowing they pushed an alpine version. But I will also call out that while it's 5 times larger it's still under 100mb, and arguably easier to maintain.

The other java images moved to a debian base image as well a while ago.

**Comment by DaneEveritt** [comment]
Closing this in favor of #1628

**Pull request closed without merging**
