### PR TITLE
add support for json5/jsonc

### LINKED ISSUE #4997: Add JSONC and JSON5 to extension JSON
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Hi is it possible that when we open a JSONC file on the web editor se we can see colors

### Describe the solution you'd like.

Just add JSONC and JSON5 to the JSON color view

### Additional context to this request.

Already talked about this in https://github.com/pterodactyl/panel/pull/3584 but not implemented and it was a PR

### PR DESCRIPTION
**Pull request by notAreYouScared**
Since v2 hasn't moved in... two years... this could've been added by now...

Closes #4997

Credit goes to: #3584 - From 2021...

### CODE REVIEW

**Comment by Sayrix** [comment]
Thank you so much!

**Review by Sayrix — COMMENTED** [review]
lgtm

**Review by camwhi-te — COMMENTED** [review]
👍🏼

**Comment by Sayrix** [comment]
Why ?

**Pull request closed without merging**
