### PR TITLE
Allow customization of the update checker's cache time

### PR DESCRIPTION
**Pull request by Deveroonie**

### CODE REVIEW

**Comment by Jelcoo** [comment]
Maybe rename to `PTERODACTYL_UPDATE_CACHE_TIME`

**Comment by Deveroonie** [comment]
done i think 😅😅😅

**Comment by DaneEveritt** [comment]
Please provide context to this PR, I don't see a specific reason to need this additional configuration option.

**Comment by Deveroonie** [comment]
Just in case someone wants to check, say, every hour instead of every 10 mins

**Comment by trenutoo** [comment]
The default time of 60 minutes should be more than enough. It's not a critical check and someone spamming cdn every minute would be a waste. 

Your change also has a breaking typo. Only one arrow, not two. =>

**Comment by DaneEveritt** [comment]
Thanks, but I don't think this is a needed change.

**Pull request closed without merging**
