### PR TITLE
Reset Passcode (Missing 500.blade.php) issue fix

### PR DESCRIPTION
**Pull request by lunar-crypticnode**
I had an issue with my reset passcode functionality where it wouldn't send any email or something without a 500.blade.php file. This will help people who are having the same issue. This pull request is related to #1521.

Note: This is a specific issue that happened to me, I noticed others were having the same issue so this would fix most people's issue. For those who aren't experiencing this issue won't do anything.

### CODE REVIEW

**Comment by gabesystems** [comment]
Really this file could be left blank because my issue was resolved by just creating the file.

**Comment by DaneEveritt** [comment]
Can you please provide a pathway for reproducing this issue and the logs related to it? I don't like just blindly accepting a PR for something I've not ever seen before.

**Comment by gabesystems** [comment]
@DaneEveritt The logs and pathway for reproducing are inside the issue thread. (#1521)

**Comment by DaneEveritt** [comment]
Closing as this isn't an issue with our defaults.

**Pull request closed without merging**
