### PR TITLE
Localization Improvements

### PR DESCRIPTION
**Pull request by kaganus**
Localization of javascript parts
Localization of some forgotten php parts
Localization fixes mainly for the new schedules
Turkish translation

### CODE REVIEW

**Comment by lancepioch** [comment]
Great work! Can you please separate the translation from the localization?

**Comment by kaganus** [comment]
you can push a reverse commit after the merge if you want, thats why i separated them into separate commits

**Comment by lancepioch** [comment]
We'd like to be able to test the fixed translations separate from your addition of a new translation.

**Comment by kaganus** [comment]
i understand that, but if you check the translation commit, it only contains new files in a new directory  resources/lang/tr which does not affect anything unless app.locale is changed. it's your own system

**Comment by lancepioch** [comment]
Thanks for the contributions, we can merge your translation in right away, but we need to manually review the translation fixes in the other files.
Therefore if you don't separate your translation and the translation fixes into separate pull requests, your translation can't be merged until we go over everything else too.

**Comment by kaganus** [comment]
wait, im confused. i thought you were talking about separating the turkish translation from the code changes. did you mean the en translation changes? if so, there are nothing changed in EN translations, and the new ones are simple copy/pastes from the previously non-localized literal strings inside php or js code. and without those new additions, new localizations will not work as they are needed at least in en translation to be displayed correctly

can you tell me what you want me to separate specifically?

**Comment by lancepioch** [comment]
`/resources/lang/tr/*` should be in its own PR so it can be merged without any code review (because there's no code to review).

**Comment by kaganus** [comment]
without these changes to localization, `/resources/lang/tr/*` will not fully work with the localization of the panel. so if this pr to the localization is somehow gets rejected, i'll have to re-do the tr translation and send another PR anyway. the tr translation inside this PR needs this PR to work

**Comment by DaneEveritt** [comment]
You can branch your language files off this branch as well which keeps them working, but also separates the PRs. As @lancepioch its really difficult to review something that both adds a bunch of translations, and also changes translator behavior.

Would be ideal to have these split, be that leaving this PR as is and splitting out one of the components, or making two new ones.

**Comment by kaganus** [comment]
i still have no idea why you both might even think these are separable commits/changes? this is really simple logic, the translations and the localization additions work with each other. translations does NOT have a meaning without these localization changes. translations are also ONLY additions of NEW files into a NEW folder, which does not affect any other single thing. testing of the localization changes IS also unaffected by the tr translations. so you can test the localization changes exactly the same way you would without the tr translations. 

"its really difficult to review something that both adds a bunch of translations, and also changes translator behavior." its actually really easy. review it as if it was 2 connected PRs. review the changes to the translator behavior, then review the translations USING the changes to the translator behavior (as you cannot review the translations without those changes anyway)

i dont know what else to say, these belong together. if you want to reject the changes to the translator behavior, then you dont have to review the translations. and i will have to send a new PR with new TR translation files which will work with the CURRENT translator behavior.

**Comment by lancepioch** [comment]
> and i will have to send a new PR with NEW TR translation files which will work with the CURRENT translator behavior.

It will help us tremendously if you do the following:

1. Submit a PR with the TR translation for the current project state (we can merge this immediately because no code changes).
2. Submit a PR with the new fixes, and you can include the additional fixed TR translations too (so we can easily identify the rest of the new translations (for EN and ES) and then test all modified pages).

This breaks up this massive PR (55 files and nearly 2k lines) into much more sizeable chunks that we can test and merge.
If you can't do that, then it'll simply take us longer to get to this PR and then even longer to test it too. Right now we have some automated testing (and are working on more), but all PR's are still currently manually tested by us too.

We appreciate the contributions, but there are lots of issues to work on. The more simple a PR is, the more likely and quickly it'll be tested and merged.
And at the very least, I'd personally love to get another translation in there too (for 0.7) and also so I can keep testing the current work I've been doing for a seamless I18N experience.

**Comment by DaneEveritt** [comment]
I have made the decision to refuse this and all future PR's from you due to your violation of the following rules from our [community code of conduct](https://github.com/Pterodactyl/Panel/blob/develop/CODE_OF_CONDUCT.md) while a member of our Discord.

```
* Trolling, insulting/derogatory comments, and personal or political attacks
* Public or private harassment
* Other conduct which could reasonably be considered inappropriate in a professional setting
```

I wish you well in your future open-source contributions, but I cannot accept these contributions from someone that willfully harassed a member of our community who volunteers their time to help others.

**Pull request closed without merging**
