### PR TITLE
Root admin allowed to use all functions even server is suspended, close #1654

### LINKED ISSUE #1654: Root Admin Should be Allowed to Use File/Database Management Even Server is Suspended
**Describe the solution you'd like**
I would like to be able to manage a server which is suspended if I am the root admin account,

**Describe alternatives you've considered**
currently, when I click on a suspended server with the root admin account, it will says suspended and I can't do anything, I would like to be able to use the database management and file management with a root admin if the server is suspended

**Additional context**

### PR DESCRIPTION
**Pull request by zKoz210**
Full access to the server is working, new message about suspended

image

### CODE REVIEW

**Comment by AreYouRlyScared** [comment]
For this, the action buttons should be hidden. And a message shown just like when an admin is viewing the server as it's installing.

**Comment by DaneEveritt** [comment]
I see this, but I will not be merging it until 1.0 final is released, thanks.

**Review by matthewpi — APPROVED** [review]

**Comment by zKoz210** [comment]
I accidentally deleted a branch and can't make edits for the latest changes. could you review the pull request and make edits?

**Comment by schrej** [comment]
Did you also delete it locally? If not you can just push it again.

**Comment by zKoz210** [comment]
and locally too

**Comment by schrej** [comment]
I've extracted the PR as `feature/root-admin-suspended`, you can either push that to your repo again and modify the PR or I'll just open a new one. That way you won't be able to commit anymore though, and the PR won't be linked to your accounts. The commits stay though.
for reference: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally

**Pull request closed without merging**
