### PR TITLE
Adding option to sftp ip on node.

### PR DESCRIPTION
**Pull request by mundotv789123**
This option is because when someone use cloudflare proxy on node the sftp connection is impossible.

### CODE REVIEW

**Comment by Doc94** [comment]
If any maintainer can link this PR to the issue #2483 (?

**Comment by Northwave** [comment]
Would love to see this in. Actually helped me to find and do the change in ServerTransformer.php manually

**Comment by drysius** [comment]
This helps other problems too, such as the dashboard schedule that when the cloudflare proxy is used, the schedule stops working because it needs sftp, which ends up giving error in the free cloudflare plan that only allows a proxy port "8443".This is just a suggestion but I think it was very strange to get ip on the side of the door, in my case I thought it best to change to "FQDN Sftp" and "FQDN Wings" 

image

**Comment by Juloos** [comment]
Any updates ? That doesn't seems really hard to implement and yet very useful for a better workflow control

**Pull request closed without merging**
