### PR TITLE
Remove aria-description

### PR DESCRIPTION
**Pull request by zKoz210**
https://fb.me/invalid-aria-prop

image

### CODE REVIEW

**Comment by notAreYouScared** [comment]
I don't have this error?

**Comment by schrej** [comment]
well, aria-description is not a valid aria tag. I'm also getting the same with Firefox, probably only appears in debug builds.

**Review by schrej — APPROVED** [review]

**Comment by TekExplorer** [comment]
shouldnt that have auto-merged?

**Comment by matthewpi** [comment]
> shouldnt that have auto-merged?

Approving a PR doesn't automatically merge it.  Only Dane can merge into the develop branch of the Panel repository anyways.

**Pull request merged**
