### PR TITLE
Teamspeak

### PR DESCRIPTION
**Pull request by Panda260**
you can now start yout teamspeak server with a serverquery password defined under startup

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
Wy is this not just 1 commit?

**Comment by trenutoo** [comment]
Your PR is based on develop branch, instead of target 1.0 develop

**Comment by QuintenQVD0** [comment]
Ow, that is wy. sorry

**Comment by Panda260** [comment]
?

**Comment by Panda260** [comment]
is everything ok with the pr?  can it be taken over like this?

**Comment by trenutoo** [comment]
No, as you can see there are over 1k changes because your base branch is wrong

**Comment by Panda260** [comment]
What branch should i use?

**Comment by trenutoo** [comment]
Your PR should be based on the same 1.0 develop branch that you are trying to merge to. Right now, you are trying to merge all V2 changes into v1 branch. 

Develop branch is for the future V2 panel release and is completely different from the current v1.

**Comment by Panda260** [comment]
Ach scheiß drauf

**Comment by danny6167** [comment]
Closed in favour of https://github.com/pterodactyl/panel/pull/5099
Thank you for your contribution.

**Pull request closed without merging**
