### PR TITLE
Tempest Hosting

### PR DESCRIPTION
**Pull request by mtotg**
Adding Tempest (https://github.com/tempest-hosting) to the pterodactyl README.

### CODE REVIEW

**Comment by WavingCatDevs** [comment]
You need to be a sponsor of the project: https://github.com/sponsors/DaneEveritt to have your host on the readme.

**Comment by PadowYT2** [comment]
> You need to be a sponsor of the project: https://github.com/sponsors/DaneEveritt to have your host on the readme.

His organization is a sponsor

**Comment by WavingCatDevs** [comment]
> > You need to be a sponsor of the project: https://github.com/sponsors/DaneEveritt to have your host on the readme.
> 
> His organization is a sponsor

Oh alright, since dane said any prs will not be merged? will that apply for sponsors in readme lol

**Comment by matthewpi** [comment]
> > > You need to be a sponsor of the project: https://github.com/sponsors/DaneEveritt to have your host on the readme.
> > 
> > 
> > His organization is a sponsor
> 
> Oh alright, since dane said any prs will not be merged? will that apply for sponsors in readme lol

Not merging PRs applies to new functionality only.

**Review by matthewpi — APPROVED** [review]

**Comment by WavingCatDevs** [comment]
> > > > You need to be a sponsor of the project: https://github.com/sponsors/DaneEveritt to have your host on the readme.
> > > 
> > > 
> > > His organization is a sponsor
> > 
> > 
> > Oh alright, since dane said any prs will not be merged? will that apply for sponsors in readme lol
> 
> Not merging PRs applies to new functionality only.

Ah, thanks for clearing that up

**Comment by DaneEveritt** [comment]
My bad, I forgot to merge this the other day when I asked you to make it. 😓

**Pull request merged**
