### PR TITLE
fix word

### PR DESCRIPTION
**Pull request by Bubbelwubbel**
Here is a spelling error.

### CODE REVIEW

**Comment by Bubbelwubbel** [comment]
image

**Comment by yesBad** [comment]
it was correct. now it isn't.

**Comment by 0x7d8** [comment]
i think you are uncorrecting it...

**Comment by Jelcoo** [comment]
The installation has already begun, so this isn't a mistake. Please learn proper English...

**Comment by YusufYaser** [comment]
begun is begin but in the past

**Comment by Bubbelwubbel** [comment]
> The installation has already begun, so this isn't a mistake. Please learn proper English...

sry, thought it was wrong...

**Comment by DaneEveritt** [comment]
If you don't have anything nice to say, just don't comment. Especially if you have no authority in this project — he was clearly just trying to help, not everyone has a strong grasp of English, including many English speakers.

Its not hard to just point out that it was correct and explain why.

@FlxiBoy1313 thanks for the PR, but as mentioned this was already correct. :)

**Comment by Bubbelwubbel** [comment]
> If you don't have anything nice to say, just don't comment. Especially if you have no authority in this project — he was clearly just trying to help, not everyone has a strong grasp of English, including many English speakers.
> 
> Its not hard to just point out that it was correct and explain why.
> 
> @FlxiBoy1313 thanks for the PR, but as mentioned this was already correct. :)

Okay, thanks.

**Comment by Bubbelwubbel** [comment]
sry for ping @DaneEveritt , but this?
image

**Comment by ArnaudLier** [comment]
> sry for ping @DaneEveritt , but this? image

It's also correct, a simple rule to get it right [is this](https://writingcenter.uagc.edu/subject-verb-agreement):
> When the subject does NOT end in the letter “s,” the verb usually will. If the subject does end in the letter “s,” the verb will NOT.

**Comment by YusufYaser** [comment]
> > sry for ping @DaneEveritt , but this? image
> 
> It's also correct, a simple rule to get it right [is this](https://writingcenter.uagc.edu/subject-verb-agreement):
> 
> > When the subject does NOT end in the letter “s,” the verb usually will. If the subject does end in the letter “s,” the verb will NOT.

He is referring to the 2 dots

**Comment by ArnaudLier** [comment]
> > > sry for ping @DaneEveritt , but this? image
> > 
> > 
> > It's also correct, a simple rule to get it right [is this](https://writingcenter.uagc.edu/subject-verb-agreement):
> > > When the subject does NOT end in the letter “s,” the verb usually will. If the subject does end in the letter “s,” the verb will NOT.
> 
> He is referring to the 2 dots

Ah sorry, I'm completely blind :joy:

**Comment by DaneEveritt** [comment]
It is not an issue I concern myself with — those errors come back from Wings so it isn't always easy to know if they are or are not going to have additional characters in them. It isn't worth anyones time to try to solve.

**Pull request closed without merging**
