### PR TITLE
Added more filters for user searching, closes #2366

### LINKED ISSUE #2366: The server owner search bar seems to only work on the email field
DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER.

For assistance installating this software, as well as debugging issues with dependencies, please use our discord server: https://discord.gg/pterodactyl

You MUST complete all of the below information when reporting a bug, failure to do so will result in closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.

**STOP: READ FIRST, AND THEN DELETE THE ABOVE LINES**

**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.0.0-rc.6
* Server's OS: CentOS 8
* Your Computer's OS & Browser: Windows 10, Edge Chromium

**Describe the bug**
We cannot search for a server owner using first name, last name or username, it only works using the email.
image
image
image

**To Reproduce**
1. Create a new server
2. In the "server owner" field, try using either the user first name or username.
3. Does not work. It only works if you type a word contained in the email field of that user.

**Expected behavior**
I should be able to type the user's username or first name to find him.

### PR DESCRIPTION
**Pull request by stijnb1234**
Added more filters to user searching

Thanks to @gabefraser for this fix.

### CODE REVIEW

**Comment by DaneEveritt** [comment]
This won't change anything unless you also pass along additional query filters in the request (which was not changed in this PR). Additionally, my understanding of this library is that you will join together these filters as an `AND` clause, and not an `OR` clause in the query, thus making the filtering _worse_, not better.

**Comment by stijnb1234** [comment]
All I've done is take the solution from him and turn it into a PR. I will test this code again tomorrow and possibly improve it.

**Comment by DaneEveritt** [comment]
Yeah this code doesn't actually do anything, other than making it accept additional `?filter[FIELD]=VALUE` params in the URL.

**Comment by stijnb1234** [comment]
I close this PR. I think someone else with more experience can do this better.

**Pull request closed without merging**
