### PR TITLE
Update egg-ark--survival-evolved.json

### PR DESCRIPTION
**Pull request by wingdings255**
Updated the list of available ark maps to include the new CrystalIsles map

### CODE REVIEW

**Comment by parkervcp** [comment]
This is more informational and not really necessary

**Comment by wingdings255** [comment]
> 
> 
> This is more informational and not really necessary

I just noticed it when I wanted to switch my server to that map and realized no one updated it since that map was released. I figured I would make a pull request to update it

**Comment by parkervcp** [comment]
> > This is more informational and not really necessary
> 
> I just noticed it when I wanted to switch my server to that map and realized no one updated it since that map was released. I figured I would make a pull request to update it

As it's a map that ships with ARK it's reasonable. This also changes if someone uploads a custom map.

**Review by parkervcp — APPROVED** [review]
LGTM

**Pull request merged**
