### PR TITLE
add: server startup password as variable

### PR DESCRIPTION
**Pull request by Panda260**
# Description

you can now start yout teamspeak server with a serverquery password defined under startup

### CODE REVIEW

**Review by parkervcp — COMMENTED** [review]
It would be better if you exported the egg from the panel instead of a manual edit.

**Comment by Panda260** [comment]
> It would be better if you exported the egg from the panel instead of a manual edit.

okey and what difference would that make? just asking

**Comment by parkervcp** [comment]
It makes sure the entire egg gets updated and time stamped.

**Comment by Panda260** [comment]
?

**Review by parkervcp — APPROVED** [review]

**Comment by matthewpi** [comment]
This PR needs to go into `1.0-develop` not `develop`.

**Comment by Panda260** [comment]
should i open a new PR?

**Pull request closed without merging**
