### PR TITLE
Update egg-paper.json

### PR DESCRIPTION
**Pull request by Sir3lit**
Changed image to the java-glibc, as multiple people have reported using the normal Java images crashes the server when people join.

### CODE REVIEW

**Comment by parkervcp** [comment]
As the base image for that image is now defunct we should be working on a new image to replace it.

I have https://github.com/parkervcp/images/tree/debian/openjdk-8-jre that I have created to do this.

**Comment by Sir3lit** [comment]
All right I'll headed to pull request when I get off work hard to edit a pull request on mobile

**Comment by Sir3lit** [comment]
Corrected egg to use `quay.io/parkervcp/pterodactyl-images:debian_openjdk-8-jre`

**Comment by DaneEveritt** [comment]
@parkervcp can we get that image merged into the core image repo to replace the other Java ones?

**Comment by parkervcp** [comment]
@DaneEveritt Will work on it.

**Pull request closed without merging**
