### PR TITLE
Add file upload progress

### PR DESCRIPTION
**Pull request by anondev-sudo**
Show file upload progres while uploading file(s).

Preview:
image

### CODE REVIEW

**Comment by matthewpi** [comment]
This is already implemented in v2 in a much different way.

Thanks for your contribution but I don't see much of a reason to add this right now when it's just going to end up being replaced.

**Comment by anondev-sudo** [comment]
Ok

**Comment by anondev-sudo** [comment]
When will be V2 released?

**Comment by mason-rogers** [comment]
When its ready

**Comment by anondev-sudo** [comment]
Is there ETA?

**Comment by trenutoo** [comment]
> Is there ETA?

No. You can view the [V2 milestone](https://github.com/pterodactyl/panel/milestone/14) to follow the progress.

**Comment by hwalker928** [comment]
Also, this PR breaks the TOS of the resource it was from.

> You may not share/send/resell this addon to others
> You may not upload this addon to any third party sites

**Pull request closed without merging**
