### PR TITLE
Update license year...

### PR DESCRIPTION
**Pull request by DomiiBunn**
Guys, it's the middle of 2019...

### CODE REVIEW

**Comment by parkervcp** [comment]
As with #1262 This really doesn't change anything...

**Comment by DomiiBunn** [comment]
It changes the date...

**Comment by DomiiBunn** [comment]
I mean i guess it's not a code contribution so some1 from the project team pr those but it's just after you notice it you just can't look away

**Comment by DaneEveritt** [comment]
As in previous comment, doesn't bother me enough nor does it invalidate the license.

**Pull request closed without merging**
