### PR TITLE
add scroll down helper to console

### LINKED ISSUE #2617: Add button to scroll to bottom of console when scrolled up and new lines come in
**Is your feature request related to a problem? Please describe.**
Transitioning from 0.7.x to 1.x.x, I miss the notification button where if a new line is outputted to console, there would be a button to jump back down to it.

**Describe the solution you'd like**
Add the notification button again.

**Describe alternatives you've considered**
Alternatives would be to have it automatically jump, although this would break accessibility for reading previous logs.
 
**Additional context**
image

### PR DESCRIPTION
**Pull request by schrej**
Adds back the scroll down helper that appears when new lines come in but the terminal isn't scrolled to the bottom.
This requires an upstream change in xterm.js (xtermjs/xterm.js#3201). Once it is released, we need to update xterm.js and can merge this PR.

I've copied the style from the search bar in the terminal right now, but we could also think about styling both properly.
image

resolves #2617

### CODE REVIEW

**Comment by trenutoo** [comment]
The referenced issue should be resolved in https://github.com/xtermjs/xterm.js/pull/3205 making this ready?

**Comment by DaneEveritt** [comment]
Not released yet https://github.com/xtermjs/xterm.js/commit/759379dfb1591fa3f6a006286dff0875bd626b2a

**Comment by notAreYouScared** [comment]
Appears that Tomorrow, May 7th, is the due day for the next release. Will make a pr to update xterm when the release is published.

**Comment by DaneEveritt** [comment]
@AreYouRlyScared can you work with @schrej and just do it all in this branch?

**Comment by schrej** [comment]
I'm only waiting for a release, then I'll update this PR.

**Review by Vasolix — APPROVED** [review]
Nice

**Pull request merged**
