### PR TITLE
Fixes file 404 error, closes pterodactyl#1613

### PR DESCRIPTION
**Pull request by rtm516**
Fixes the issue referenced in #1613

### CODE REVIEW

**Comment by MatthewSH** [comment]
Have you tested this for any vulnerabilities considering you're removing the url encode method?

**Comment by DaneEveritt** [comment]
The urlencode isn't for security, its to prevent browsers from struggling to correctly handle files with weird characters. The output is technically already escaped by blade's render engine.

**Comment by schrej** [comment]
The script Matthew suggested wouldn't get escaped by blade. Those are all regular characters that can easily be present in a html document. Escaping mostly boils down to `<` and `>`.

For javascript to work in the `href` it needs to *start* with `javascript:`, i've quickly tested the string below and that doesn't show the alert.
```html
<a href="/test;javascript:alert('Test')">test</a>
```
As we start the `href` part with a path, we should be fine, `javascript:` can't appear at the beginning.

**Comment by lancepioch** [comment]
Blade already escapes everything by default, so the question is does it escape too much and break at all? Or does the average filename still work correctly.

**Comment by DaneEveritt** [comment]
@rtm516 please switch the base for this PR from pterodactyl:develop to `pterodactyl:0.7-develop`

**Pull request closed without merging**
