### PR TITLE
Change MB to MiB on admin pages

### PR DESCRIPTION
**Pull request by Jcodeerd**
This PR changes MB to MiB which was already changed on the frontend, but not on the admin pages.

### CODE REVIEW

**Comment by matthewpi** [comment]
If we are going to change these, you should change the rest of the usages of `B` suffixes.  Specifically on the node pages as well.

**Comment by Jcodeerd** [comment]
Ah, I forgot those. I'll change those tomorrow!

**Comment by Jcodeerd** [comment]
I think those are all, unless I missed any.

**Comment by matthewpi** [comment]
I just made these changes myself (https://github.com/pterodactyl/panel/commit/2f4a60c9615af0f06b025c3936ade89dc87ba974), I'm not sure how you were making these changes but it is always easier to use the find and replace functionality of an editor.

**Pull request closed without merging**
