### PR TITLE
fixing CSRF required even with API key

### PR DESCRIPTION
**Pull request by filpecosta**

### CODE REVIEW

**Comment by devnote-dev** [comment]
This PR would remove CRSF checks for browsers entirely which is a big security issue. I would also like to point out (as previously mentioned from the initial discussion in the Discord server) that **you should not be making such requests from the browser if you do not want to deal with CSRF/cookies.** Using API keys for requests in the browser is _not_ the way to go about structuring your application, and there are more than enough resources available on how to do so properly. I don't believe #4723 is valid here and should be closed as it is not a panel issue.

**Comment by filpecosta** [comment]
Actually in my case I don't use the panel for the public, but without it, the error is occurring not in the Browser, but in the API call even in Postman :(

**Comment by filpecosta** [comment]
Actually in my case I don't use the panel for the public, but without it, the error is occurring not in the Browser, but in the API call even in Postman :(

**Comment by ghost** [comment]
> Actually in my case I don't use the panel for the public, but without it, the error is occurring not in the Browser, but in the API call even in Postman :(

If you don't use it in public, you can still use your modified Version of the Panel, just keep it in your Fork, if People actually need this Change, they can just build the Panel from your Fork-Source, because the way you are implementing it presents a serious security issue since... well People sometimes (surprisingly) update their Software.

**Comment by Sewdohe** [comment]
I am also having this issue when making API requests from postman as well as the curl application. Is this the only fix?

**Pull request closed without merging**
