### PR TITLE
Update ServersController.php

### PR DESCRIPTION
**Pull request by Nobody196**
(!$server->installed) echoes false which won't save to the database

### CODE REVIEW

**Comment by ZeProf2Code** [comment]
This resolved my bug that I had for so long where I can't change the install state!

**Comment by Nobody196** [comment]
> This resolved my bug that I had for so long where I can't change the install state!

🙏 thanks for catching that

**Comment by lancepioch** [comment]
The code doesn't seem correct, but the fix doesn't quite fit either I think. Take a look: https://github.com/pterodactyl/panel/blob/0f8dcabb45aa80e1659bf35874fc048e6d0e7170/app/Models/Server.php#L90

It can be 0-2

**Comment by Nobody196** [comment]
> The code doesn't seem correct, but the fix doesn't quite fit either I think. Take a look:
> 
> https://github.com/pterodactyl/panel/blob/0f8dcabb45aa80e1659bf35874fc048e6d0e7170/app/Models/Server.php#L90
> 
> It can be 0-2

Maybe I'm a bit confused but the fix can only echo 0 or 1 based on true of false

**Comment by lancepioch** [comment]
Whoops, didn't even notice that. Looks good then.

**Comment by DaneEveritt** [comment]
This change doesn't make sense, you can only get here if the server is installed or not, so all we're doing is toggling the state between true & false, which the existing code does just fine?

**Pull request closed without merging**
