### PR TITLE
Added filesystem as cache option

### PR DESCRIPTION
**Pull request by XMGamingMaster**

### CODE REVIEW

**Comment by DaneEveritt** [comment]
Filesystem is not supported as we make use of the tagging system for the cache. If we want to support files you'd need to also look through the code and find anywhere using tags and see if we can either remove those tags, or handle not tagging for file cache.

**Comment by XMGamingMaster** [comment]
We are currently using Filesystem as cache option and everything seems to work perfectly fine.

**Comment by DaneEveritt** [comment]
It might be better in 0.7, but I know there were places using tagging, so you might want to do a check through the code to make sure those places no longer exist.

**Comment by XMGamingMaster** [comment]
Yeah, i will do that.

**Pull request closed without merging**
