### PR TITLE
Make interface mobile responsive

### LINKED ISSUE #1949: Mobile view not properly formatted
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: Beta 1.0
* Server's OS: Ubuntu 1804
* Your Computer's OS & Browser: Andorid 10 / Chrome 

**Describe the bug**
Portrait mode, mobile view doesn't properly adjust elements 
Screenshot_20200419-142306_Chrome
Screenshot_20200419-142258_Chrome

**To Reproduce**
View on mobile. 
Current device is a Note 10+ @ 3040x1440

**Expected behavior**
Elements to dynamically format to mobile devices. 

Landscape looks fine 
Screenshot_20200419-142213_Chrome

### PR DESCRIPTION
**Pull request by LeCodeCo**
Makes a bunch of the pages mobile responsive.

Closes #1949

### CODE REVIEW

**Comment by gabefraser** [comment]
Are we still waiting for the conflicts to be amended before this can be merged with the develop branch?

**Comment by LeCodeCo** [comment]
Everything is responsive now! Let me know if any changes need to be made.

**Comment by Sir3lit** [comment]
I wish everyone was just one big commit....

**Comment by matthewpi** [comment]
> I wish everything was just one big commit....

That will probably need to be fixed before this gets merged as having 20 merge commits will mess with the entire commit history of the repository.

**Pull request merged**
