### PR TITLE
Add group input to upgrade command

### PR DESCRIPTION
**Pull request by Boy132**
This allows the user to also enter a group that is used for _chown_. Usefull if your user isn't the same as your group.

### CODE REVIEW

**Comment by Rhydium** [comment]
You practically didn't change anything as the command being runned is `chown -R {$user}:{$user}`, so when you choose `www-data` the command being executed would already be `chown -R www-data:www-data`.

**Comment by Boy132** [comment]
> You practically didn't change anything as the command being runned is `chown -R {$user}:{$user}`, so when you choose `www-data` the command being executed would already be `chown -R www-data:www-data`.

I changed the command to be `chown -R {$user}:{$group}`. This allows the group to be different from the user which is the whole point of the PR.

**Comment by DaneEveritt** [comment]
Well if you're going to do that it should accept a `--group` flag as well, because otherwise you cannot actually set a different user and group unless it is already configured that way on the system.

Also, any variable that is more than a word should be `camelCase` not `snake_case`. :)

**Comment by Boy132** [comment]
> Well if you're going to do that it should accept a `--group` flag as well, because otherwise you cannot actually set a different user and group unless it is already configured that way on the system.
> 
> Also, any variable that is more than a word should be `camelCase` not `snake_case`. :)

Made some changes. :) Should be good now.

**Review by Kaesewuerfel — APPROVED** [review]

**Pull request merged**
