### PR TITLE
Steam ID for Insurgency incorrect

### PR DESCRIPTION
**Pull request by ozzygit**
Modified game (steam) id from Insurgency MOD (old - no longer used) to Insurgency 2014 (pre-sandstorm - still very popular)

### CODE REVIEW

**Comment by rtm516** [comment]
I'm not sure this is correct as both AppID's are registered as insurgency dedicated server
https://steamdb.info/app/17705/
https://steamdb.info/app/237410/

**Comment by ozzygit** [comment]
What I said is correct.

17705 - Insurgency Mod (Note the Mod) HL2 Dedicated Server
237410 - Insurgency Dedicated Server
222880 - Insurgency
581320 - Insurgency Sandstorm
581330 - Insurgency Sandstorm Dedicated Server

**Comment by rtm516** [comment]
> 237410 - Insurgency Dedicated Server

After some research can confirm that this is correct.

**Comment by arcdigital** [comment]
due to some annoying git stuff we had to re-do this update in #1652 which is now merged and will go out in the v0.7.15 release. I gave you credit on the commit.

**Pull request closed without merging**
