### PR TITLE
Checkbox & Dropdown for Startup Variables

### LINKED ISSUE #570: Drop-down list of values for variables
Make it possible to preset several values ​​for variables . 
And allow users to select from the drop-down list this values.

Like : http://prntscr.com/g2w13o

### LINKED ISSUE #1493: multiple choices for Egg Variables
**Is your feature request related to a problem? Please describe.**
Some config is "true" or "false", if there will be an Drop down box or Selection box will be easy

**Describe the solution you'd like**
Add more choice of the Egg Variables. Like Drop down box, Selection box, Slider etc.
Just like the configuration options in WHMCS

**Additional context**
Here is example in WHMCS I hope ptero can support these type of Egg Variables
chrome_2019-02-21_14-22-49

### PR DESCRIPTION
**Pull request by Boy132**
This PR introduces checkboxes for variables of type `boolean`  and dropdowns for variables with an `in` rule.
I also added a `readOnly` property to the Switch component.

**I'm fairly new to React so please excuse if my code is unclean or unoptimized. (Feel free to leave a review!)**

~The only "problem" left is that the new introduced elements are still interactable when a variable doesn't have the `Users Can View` permission. The actual value does not change however. Solutions for this problem are more than welcome. :)~

This would resolve #1493 and also resolve #570

Example: (Garry's Mod Egg)
image
image
_(Shown changes to the Garry's Mod egg are **not** included!)_

### CODE REVIEW

**Comment by DaneEveritt** [comment]
You're going to run into a wall with the changes @matthewpi is making in V2. You probably want to be working off the V2 branch itself, and not develop.

**Comment by Boy132** [comment]
> You're going to run into a wall with the changes @matthewpi is making in V2. You probably want to be working off the V2 branch itself, and not develop.

Oh, I thought matthewpi's changes are purely visual changes to the admin area? Anyways, I will check out the v2 branch and see what's going on there. :D

EDIT: I did some testing with the current v2 branch and the changes made to `VariableBox.tsx` could be transferred over. I can add these changes to the v2 branch if this PR gets merged. :)

**Comment by DaneEveritt** [comment]
Sorry, not trying to ignore this PR, I just have a lot going on right now and won't have time to look until the new year most likely. We'll want to just roll this out with V2 though, not V1 if that helps guide any work that needs to happen. (cc @matthewpi )

**Comment by Boy132** [comment]
> Sorry, not trying to ignore this PR, I just have a lot going on right now and won't have time to look until the new year most likely.

No problem, take your time. :)

> We'll want to just roll this out with V2 though, not V1 if that helps guide any work that needs to happen. (cc @matthewpi )

In that case I will make a separate PR for the v2 branch soon.

**Comment by FoksVHox** [comment]
@Boy132 Or, you could change the taget branch to v2, it would be easier

**Comment by Boy132** [comment]
> @Boy132 Or, you could change the taget branch to v2, it would be easier

This PR is only for the client area and I would like to also apply these changes to the admin area of v2.

**Comment by FoksVHox** [comment]
> > @Boy132 Or, you could change the taget branch to v2, it would be easier
> 
> 
> 
> This PR is only for the client area and I would like to also apply these changes to the admin area of v2.

If you change the target branch, to v2, you'd be able to do that, assuming that page has been refactored

**Comment by matthewpi** [comment]
In terms of v2, the plan was to add different variable types, like password, switch, select, etc.  This PR is fine as that functionality is going to be further down the road and when that happens this logic will just end up being removed.

**Review by matthewpi — APPROVED** [review]

**Pull request merged**
