### PR TITLE
Deploy Node and Create Allocations with Artisan

### PR DESCRIPTION
**Pull request by JackW6809**
Requires https://github.com/pterodactyl/panel/pull/3396
Building off of my feature request #3277 I have been able to make my request almost fully complete. All I need now is for Wings to be automatically configured and it will be done!

### CODE REVIEW

**Comment by JackW6809** [comment]
I noticed that the Node.php file located in app/Models lines 141-192 actually can output a node's configuration but I am not too sure on how to utilize it so maybe someone can make use of it I am not too sure. If it can be utilized then my request can be complete fully as the output can be saved as the config.yml file.

**Comment by Fabian-Ser** [comment]
I rather think that returning an output of the config (which can be turned on with a flag, for example) is more convenient than storing the file on the server. If this is what you meant I am happy to help if desired.

**Comment by JackW6809** [comment]
@Fabian-Ser I mean, if it means that storing it as a file is enabled by a flag then sure that would be great. I have asked my friend who specialises in PHP to take a look and if he cannot figure it out I would be more than glad for you to contribute!

**Comment by JackW6809** [comment]
@Fabian-Ser Hi, we came to the conclusion you would be best as you probably know the structure best. Is there a way I can contact you so we can stay in contact further?

Kind Regards,
Jack W.

**Comment by JackW6809** [comment]
That commit above will be one of my final ones for this PR as I have completed the integration of my feature request #3277. Any more commits will probably be small tweaks or grammatical changes.

**Comment by JackW6809** [comment]
Since Fabian is the one making the node creation command I have removed it from my PR. #3319

**Pull request closed without merging**
