### PR TITLE
Add configurable OAuth login methods

### PR DESCRIPTION
**Pull request by AlexProgrammerDE**
Hi there! This PR adds the option for users to log in using OAuth. This PR is based off #1964. It was abandoned by its author 8 months ago. (To be exact, on 1 April 😆). This PR overall fixes up the entire code that PR added and reuses some of the panels UI components to look more like it belongs in the panel. I am quite new to PHP, but do usually develop with JavaScript and tailwindcss, so I may ask back a few times more about a change request in a review than a normal PHP dev. PR is open for commits from maintainers, and I do also accept PRs to my fork! hmu in the pterodactyl support discord server if you want to talk with me about this PR directly via chat without spamming everyone with emails. (`Pistonmaster#0001`)

Here are the shipped OAuth providers:
built-in (socialite ships with these): Facebook, Twitter, LinkedIn, Google, GitHub, GitLab, and Bitbucket
Additional bundled providers (Those are quite popular, so I added them as well): Discord, Microsoft and Apple

Screenshots of the added UI:
<details>
  <summary>Screenshots</summary>
  
  
  
  
  
</details>

TODO:
- [ ] Review UI again and make all components match up with ones from other blades if they mismatch.
- [ ] Test every single driver to make sure it works.
- [ ] Write full [documentation](https://github.com/pterodactyl/documentation) for setting up OAuth providers and basic guiding for adding custom OAuth providers. 

### !!! Important !!!
Please do not send a +1 message in here or ask when it will be merged. Nor review this PR if you are not a pterodactyl team member or have actual change requests to the code! [Last time,](https://github.com/pterodactyl/panel/pull/1964#issuecomment-811354795) the amount of messages spammed the inbox of pterodactyl team members, and they were forced to lock conversation on the PR. (I do 100% stand that decision as a dependabot user 😄)

### CODE REVIEW

**Comment by trenutoo** [comment]
The original PR is not abandoned and rather no one had time to review such a huge change, especially with this being a security one.

FYI the admin panel is also being rewritten in React for V2

**Comment by AlexProgrammerDE** [comment]
> The original PR is not abandoned and rather no one had time to review such a huge change, especially with this being a security one.

The original author deleted their fork and didn't do any commits afterwards. Some UI stuff was really just thrown together, and it is easy to see the traces of copying and pasting code without changing titles and descriptions.

> FYI the admin panel is also being rewritten in React for V2

Have seen it in announcements. If it's not a big issue, I will just rebase this onto the v2 branch and then reroute this PR to that. I was just unsure whether the team would allow a change like this before the v2 release.

**Comment by finnie2006** [comment]
Maybe you can make an free addon from it for now and put it on pterodactylmarket

**Comment by jer3m01** [comment]
> The original PR is not abandoned and rather no one had time to review such a huge change, especially with this being a security one.

Can confirm.

> The original author deleted their fork and didn't do any commits afterwards.

The original PR was made over 3 years ago, before V2 was even announced. Because of the changes in V2 I closed the PR and waited for it to be released.
Once released I recoded OAuth for the new panel (>2 years ago). 

The PR had some feedback which I followed and was ready for full review. 

I would like to note I was in contact with someone from the staff and asked him if he could forward my request to review in the team's private channel. He did and and the team was going to see when they had free time.

It stayed unreviewed for a long time and a wave of community users started approving the PR which lead the team to lock the discussion because of spam. At that point the PR was outdated, I rebased it and changed some code. 
Since it was locked I couldn't comment nor close my own PR. So I sent a message in the public development channel on discord (you can search for it if you want), I mentioned Dane saying I updated the PR and asked if anything additional should be done. I was once again ignored in addition to the few previous months.

On the 17th of April 2021 one of the team members sent a message in their private channel that they wouldn't accept the PR as the negatives far outweighed the main positive.
Other members in the channel agreed.

No public mentions of that message was made neither on discord or github. The only way I knew was through my contact who forwarded me the message (don't even think the team knows I've seen it, might be wrong).


I hope the team starts being professional and doesn't outright ignore this PR or your messages. 
Best of luck in getting this finished and approved.

**Comment by finnie2006** [comment]
dead again

**Comment by kylejschultz** [comment]
Any update on this PR? Would really love to implement OAuth into my environment with Pterodactyl.

**Comment by DaneEveritt** [comment]
Per the changes to the PR policy I am going to be closing this PR. Thank you all for putting so much time into this, but I cannot justify merging this in and managing to maintain it over time and ensure it is sufficiently secure across the board.

https://github.com/pterodactyl/panel/blob/develop/CONTRIBUTING.md

#4026 might be a better middle-ground for all of this, and allow other authentication methods to be used successfully in the future.

**Comment by dorianim** [comment]
Should #4026 be implemented, you can use [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy).

**Comment by DaneEveritt** [comment]
@dorianim mind commenting on that issue with some details just for reference there too?

**Comment by sailorbob134280** [comment]
This ever going to be supported? It's taken 2 ignored PRs. When you have so many +1s on a PR that you need to lock it, maybe the answer isn't to just ignore it... just sayin.

**Pull request closed without merging**
