### PR TITLE
Update Script For Ptero Panel

### PR DESCRIPTION
**Pull request by tmunsch**
# Pterodactyl Panel Update Script

> Compatibility: Pterodactyl 1.7+

## Usage

```
cd /var/www/pterodactyl
chmod +x update
./update
```

## Functionality
- Checks for proper **PHP** and **Composer** versions
- Set's Panel in Maintenance Mode
- Downloads Updated files for Latest Release
- Updates **Dependencies**
- Clears Cache for Views and Routes
- Performs Database Updates
- Sets the proper file permissions based on OS and Web Server Type
- Restarts Worker Queue
- Set's Application to **Live**

## Concerns
- Runs completely Unattended with no prompts.... is a feature?
- Bypasses Yes/No Prompts for Running Composer as Root
- Colors Might be too much

## Proposed Future Update/Functionality
- Switch commands to bypass certain steps ( ex: ./update -nodb -nophpcheck -nocacheclear

### CODE REVIEW

**Comment by FoksVHox** [comment]
This has been attempted before in #4103

**Comment by FoksVHox** [comment]
This has been attempted before in #4103. However, this is already possible with `php artisan p:upgrade`

**Comment by LucaTanks** [comment]
> This has been attempted before in #4103. However, this is already possible with `php artisan p:upgrade`

Am I right in saying that the upgrader is set to be removed, as it’s not working at the moment and replaced with a solution like this though

**Comment by gOOvER** [comment]
> This has been attempted before in #4103. However, this is already possible with `php artisan p:upgrade`

https://github.com/pterodactyl/panel/pull/4103#issuecomment-1141524522

This PR here and #4103 are differnt things ;)

**Comment by camwhi-te** [comment]
Pretty sure this is quite unlikely to be added as it isn't an Artisan command, eg: `php artisan p:[command name]`.

**Comment by LucaTanks** [comment]
Dane has said he would make a bash script for this, I'm guessing the PR is to do that for him

**Pull request closed without merging**
