### PR TITLE
[WIP] Don't do package discovery on live app, fixes #818

### LINKED ISSUE #818: composer install --no-dev artisan package:discover fails on missing panel.settings DB table
* Panel or Daemon: Panel
* Version of Panel/Daemon: v0.7.0-beta2
* Server's OS: Fedora 27 (Linux 4.14.5-300.fc27.x86_64)
* Your Computer's OS & Browser: (Windows 10 - Chrome | Fedora 27 (gnome) - Chrome)

## Add Details Below:

Am I missing or using wrong documentation? It's taken almost two days to try to install Panel...
I'm using Docs for v0.7:
https://docs.pterodactyl.io/v0.7/docs

```
composer install --no-dev
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

                                                                               
  [Illuminate\Database\QueryException]                                         
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'panel.settings'   
  doesn't exist (SQL: select * from `settings`)                                
                                                                               

                                                                               
  [Doctrine\DBAL\Driver\PDOException]                                          
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'panel.settings'   
  doesn't exist                                                                
                                                                               

                                                                               
  [PDOException]                                                               
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'panel.settings'   
  doesn't exist                                                                
                                                                               

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```

I have no problem doing a more manual version of the install instead of `composer install --no-dev` if there are so many issues with the build process, I'm just not sure where look for manual instructions.

Thanks for any assistance on this, and I apologize if I've missed something obvious!

### PR DESCRIPTION
**Pull request by lancepioch**

### CODE REVIEW

**Comment by DaneEveritt** [comment]
Why?

**Comment by arcdigital** [comment]
This is wrong and will break the panel since the packages cache is not included in the app (on purpose, since we're making them do composer install).

**Comment by lancepioch** [comment]
Package discovery is only for development purposes, not having this won't break the panel

**Comment by lancepioch** [comment]
Wrong fix.

**Comment by arcdigital** [comment]
This isn’t true, look at the default Laravel composer file. This is part of the new 5.5 auto discovery where you don’t need to register service providers.

**Pull request closed without merging**
