### PR TITLE
Added forge build number support

### PR DESCRIPTION
**Pull request by NgLoader**

### CODE REVIEW

**Comment by parkervcp** [comment]
If this is identical to what you sent to my repo then you have a bad install script.

**Comment by NgLoader** [comment]
I only edited you script

**Comment by parkervcp** [comment]
I double checked and I had 2 forge-enhanced nests. One was not the one I wrote.

I recommend switching the grep to `grep  -o -e '[1].[0-9]*.[0-9]* - [0-9]*.[0-9]*.[0-9]*.[0-9]*'` instead of the longer one in that old one. I am recommending this on the eggs repo as well.

**Comment by NgLoader** [comment]
Okay thank I test it tomorrow with your regex

**Comment by NgLoader** [comment]
Okay fail...

**Comment by DaneEveritt** [comment]
Please resolve the conflicts.

**Comment by NgLoader** [comment]
> 
> 
> Please resolve the conflicts.

done

**Pull request merged**
