### PR TITLE
Update Paper egg

### PR DESCRIPTION
**Pull request by ruscalworld**
[Paper API v2](https://papermc.io/api/docs/) has been released recently and API v1 is now deprecated. I've updated install script and it uses new API now. 
Also, today there was an announncment that Paper [will support only Java 11+](https://papermc.io/forums/t/java-11-mc-1-17-and-paper/5615) after release of Minecraft 1.17. So, I've updated Docker image.

### CODE REVIEW

**Review by Aurelien30000 — APPROVED** [review]

**Comment by M-AlNoaimi** [comment]
I think I remember seeing someone PR'ing a V2 update to the eggs on @parkervcp's repo..

**Comment by parkervcp** [comment]
I'll update this with the egg from my repo instead. I try to update the and regularly pr over.

**Comment by DaneEveritt** [comment]
Can we please get that PR here going ASAP? Gonna need to go out in a release which can take some time all things considered.

**Comment by parkervcp** [comment]
I will be submitting a PR soon

**Pull request closed without merging**
