### PR TITLE
Update copyright notices to 2018

### PR DESCRIPTION
**Pull request by MrKaKisen**
The title says it all! 👍 

I was unsure if this was something to include in the changelog, so I didn't.

### CODE REVIEW

**Comment by MrKaKisen** [comment]
Sorry, I accidentally pushed a merge commit. Ignore the second commit, it's only the first one that matters (`cbb66bc`)

**Comment by MrKaKisen** [comment]
Any updates on this?

**Comment by DaneEveritt** [comment]
I'll get around to it at some point. Its not of any major concern for me to merge right now is all. 👍

**Comment by MrKaKisen** [comment]
Alright, thanks for replying 👍

**Comment by DaneEveritt** [comment]
Not going to be merging this because I've slowly been removing all of those license headers from the code base, and the year being incorrectly doesn't really bother me (or invalidate the license of the code).

**Pull request closed without merging**
