### PR TITLE
egg(teamspeak): fix database support

### PR DESCRIPTION
**Pull request by Wunderharke**
I know pull requests from new contributors aren't usually allowed, but this is a very small change that gave me a headache the other day.
It fixes database support for MariaDB by copying a necessary library. See https://forum.teamspeak.com/threads/132925-unable-to-load-database-plugin-library-libts3db_mariadb-so

### CODE REVIEW

**Review by trenutoo — CHANGES_REQUESTED** [review]
Thanks for taking the time to contribute to the project. I'm afraid there are some breaking issues:

* This redirection breaks the tar step causing the whole installation to fail. You either want to use `&&` or perform the copy on a different line.

**Comment by Wunderharke** [comment]
Sorry for the late response and the wrong pull request. I've updated the commit, and it should be working now.
I've moved the command to a new line and also escaped the slashes.

**Review by trenutoo — APPROVED** [review]
LGTM. Thanks for contributing :+1:

**Comment by matthewpi** [comment]
If you are able to can you rebase your changes on top of `1.0-develop`?  When I switched the branch the PR will merge into, the commits develop has ahead of 1.0-develop persisted.

**Comment by Wunderharke** [comment]
Should be correct and on top of `1.0-develop` now.

**Pull request merged**
