### PR TITLE
Add emotion/react

### PR DESCRIPTION
**Pull request by notAreYouScared**
Fixes building with `yarn build:production`

### CODE REVIEW

**Review by DaneEveritt — CHANGES_REQUESTED** [review]
I need to dig into this, we don't use emotion anywhere so the fact that this is blocking installs is concerning (given that it works fine for me as well).

**Comment by trenutoo** [comment]
> I need to dig into this, we don't use emotion anywhere so the fact that this is blocking installs is concerning (given that it works fine for me as well).

The issue only occurs if you specify production, we've tested this in a call, and it fails to build only on brand new install without any prior installs on the OS (ex. new VPS). You probably have it already as dev dependency somewhere from other projects or builds?

**Comment by DaneEveritt** [comment]
Our build process literally runs without issue and is able to generate compiled assets?

**Comment by DaneEveritt** [comment]
```
vagrant@pterodactyl:~/app$ node -v
node -v
v14.15.4
vagrant@pterodactyl:~/app$ rm -rf node_modules/
vagrant@pterodactyl:~/app$ yarn
yarn install v1.22.5
[1/5] Resolving packages...
[2/5] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/5] Linking dependencies...
warning " > react-ga@3.1.2" has unmet peer dependency "prop-types@^15.6.0".
warning " > styled-components@5.2.1" has unmet peer dependency "react-is@>= 16.8.0".
warning " > styled-components-breakpoint@3.0.0-preview.20" has incorrect peer dependency "@types/styled-components@^4.1.19".
warning " > styled-components-breakpoint@3.0.0-preview.20" has incorrect peer dependency "styled-components@>= 1 <= 4".
warning " > xterm-addon-search-bar@0.2.0" has incorrect peer dependency "xterm-addon-search@^0.5.0".
warning " > redux-devtools-extension@2.13.8" has unmet peer dependency "redux@^3.1.0 || ^4.0.0".
[4/5] Building fresh packages...
[5/5] Cleaning modules...
Done in 139.42s.
vagrant@pterodactyl:~/app$ yarn run build:production
yarn run v1.22.5
$ yarn run clean && cross-env NODE_ENV=production ./node_modules/.bin/webpack --mode production
$ cd public/assets && find . \( -name "*.js" -o -name "*.map" \) -type f -delete
Hash: cd052b08cb81697412b7
Version: webpack 4.43.0
Time: 39078ms
Built at: 01/28/2021 4:30:32 AM
                      Asset      Size  Chunks                                Chunk Names
         bundle.af5222cd.js   857 KiB       4  [emitted] [immutable]  [big]  main
        console.71e29e73.js  6.71 KiB       0  [emitted] [immutable]         console
         editor.74bf5a16.js  2.53 KiB       1  [emitted] [immutable]         editor
   feature.eula.1f0de279.js   3.1 KiB       2  [emitted] [immutable]         feature.eula
         graphs.907f7a2f.js  3.35 KiB       3  [emitted] [immutable]         graphs
              manifest.json  1.27 KiB          [emitted]
vendors~console.0a83c7ce.js   310 KiB       5  [emitted] [immutable]  [big]  vendors~console
 vendors~editor.95557289.js   533 KiB       6  [emitted] [immutable]  [big]  vendors~editor
 vendors~graphs.c021c2d6.js   155 KiB       7  [emitted] [immutable]         vendors~graphs
Entrypoint main [big] = bundle.af5222cd.js
  [2] ./resources/scripts/state/server/index.ts + 5 modules 6.27 KiB {4} [built]
      | ./resources/scripts/state/server/index.ts 2.94 KiB [built]
      | ./resources/scripts/state/server/socket.ts 294 bytes [built]
      | ./resources/scripts/state/server/files.ts 715 bytes [built]
      | ./resources/scripts/state/server/subusers.ts 734 bytes [built]
      | ./resources/scripts/state/server/schedules.ts 812 bytes [built]
      | ./resources/scripts/state/server/databases.ts 812 bytes [built]
  [3] ./resources/scripts/api/http.ts 2.8 KiB {4} [built]
 [10] ./resources/scripts/plugins/useFlash.ts 192 bytes {4} [built]
 [19] ./resources/scripts/helpers.ts 1.84 KiB {4} [built]
 [31] ./resources/scripts/theme.ts + 1 modules 2.06 KiB {4} [built]
      | ./resources/scripts/theme.ts 164 bytes [built]
      |     + 1 hidden module
 [37] ./resources/scripts/state/index.ts + 7 modules 6.66 KiB {4} [built]
      | ./resources/scripts/state/index.ts 403 bytes [built]
      | ./resources/scripts/state/flashes.ts 1.7 KiB [built]
      | ./resources/scripts/state/user.ts 2.27 KiB [built]
      | ./resources/scripts/state/permissions.ts 1.11 KiB [built]
      | ./resources/scripts/state/settings.ts 181 bytes [built]
      | ./resources/scripts/state/progress.ts 428 bytes [built]
      | ./resources/scripts/api/account/updateAccountEmail.ts 296 bytes [built]
      | ./resources/scripts/api/getSystemPermissions.ts 284 bytes [built]
 [41] ./resources/scripts/plugins/usePermissions.ts 1.02 KiB {4} [built]
 [55] ./resources/scripts/plugins/useDeepMemoize.ts 250 bytes {4} [built]
 [62] ./node_modules/react-transition-group/esm/CSSTransition.js + 3 modules 14.4 KiB {4} [built]
      |    4 modules
 [67] ./resources/scripts/api/server/getServer.ts 3.02 KiB {4} [built]
 [76] ./node_modules/@emotion/is-prop-valid/dist/is-prop-valid.browser.esm.js + 1 modules 4.41 KiB {4} [built]
      |    2 modules
 [91] ./resources/scripts/plugins/usePersistedState.ts 687 bytes {4} [built]
 [92] ./resources/scripts/api/server/files/saveFileContents.ts 969 bytes {4} [built]
[115] multi react-hot-loader/patch ./resources/scripts/index.tsx 40 bytes {4} [built]
[179] ./resources/scripts/index.tsx + 698 modules 1.58 MiB {4} [built]
      | ./resources/scripts/index.tsx 554 bytes [built]
      | ./resources/scripts/i18n.ts 736 bytes [built]
      | ./resources/scripts/routers/DashboardRouter.tsx 1.62 KiB [built]
      | ./resources/scripts/routers/ServerRouter.tsx 11 KiB [built]
      | ./resources/scripts/routers/AuthenticationRouter.tsx 1.55 KiB [built]
      | ./resources/scripts/assets/css/GlobalStylesheet.ts 2.64 KiB [built]
      | ./resources/scripts/api/interceptors.ts 883 bytes [built]
      | ./resources/scripts/TransitionRouter.tsx 1.03 KiB [built]
      | ./resources/scripts/hoc/RequireServerPermission.tsx 622 bytes [built]
      | ./resources/scripts/api/getServers.ts 1.68 KiB [built]
      | ./resources/scripts/api/account/getApiKeys.ts 674 bytes [built]
      | ./resources/scripts/api/account/deleteApiKey.ts 263 bytes [built]
      | ./resources/scripts/plugins/useWebsocketEvent.ts 889 bytes [built]
      | ./resources/scripts/plugins/Websocket.ts 4.92 KiB [built]
      | ./resources/scripts/api/server/getWebsocketToken.ts 363 bytes [built]
      |     + 684 hidden modules
    + 265 hidden modules
Done in 43.75s.
```

Cannot reproduce. Furthermore:

```
vagrant@pterodactyl:~/app$ yarn why @emotion/react
yarn why v1.22.5
[1/4] Why do we have the module "@emotion/react"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
error We couldn't find a match!
Done in 0.63s.
```

**Pull request closed without merging**
