### PR TITLE
Added a hostname variable.

### PR DESCRIPTION
**Pull request by ir-3**

### CODE REVIEW

**Comment by DaneEveritt** [comment]
Please make sure to export these through the Panel so that the exported_at timestamps get updated as well. :)

**Comment by ir-3** [comment]
I will get to that in a bit. Sorry.

**Comment by rouing** [comment]
Hostname should be handled through server.cfg

**Comment by DaneEveritt** [comment]
I agree with @rouing on this, seems better handled though a config file.

**Pull request closed without merging**
