### PR TITLE
Update to XtermJS v5.0.0

### PR DESCRIPTION
**Pull request by notAreYouScared**
Updated to XtermJS v5 along with the corresponding dependencies.

When searching the activeMatchColor is known to be broken, currently matched search results are highlighted in white
https://github.com/xtermjs/xterm.js/issues/4199

- [x] Loads without error
- [X] Test search
- [X] Test commands
- [X] Test resize

LTNV0jSMC0

### CODE REVIEW

**Comment by saboooor** [comment]
Xterm seems to be slow on v5

**Comment by matthewpi** [comment]
Could you split out the z-index changes into it's own PR?  I'm going to update Xterm separately and replace the existing Terminal component entirely to fix a bunch of issues related to resizing and cleanup that I've experienced with the current implementation.

**Comment by notAreYouScared** [comment]
> Could you split out the z-index changes into it's own PR? I'm going to update Xterm separately and replace the existing Terminal component entirely to fix a bunch of issues related to resizing and cleanup that I've experienced with the current implementation.

https://github.com/pterodactyl/panel/pull/4579

I'll revert it on this branch when i get home, attempting to revert with the web version is cancer

**Comment by matthewpi** [comment]
I believe I did this myself when I did all the vite changes.

Closing for now, the z-index searchbar stuff was separated out and merged.

**Pull request closed without merging**
