### PR TITLE
admin(eggs): add `force_outgoing_ip` option

### LINKED ISSUE #3841: Set the outgoing IP correctly when using multiple IPs on one node
### Describe the feature you would like to see.

By default docker always uses the first interface for outbound traffic. This can lead to issues with self-advertising servers like CS:GO as reported in #459.

### Describe the solution you'd like.

Docker has added support for a new label that allows to set the outbound IP of a docker network: https://github.com/moby/libnetwork/pull/2454

In order to support this we would need to create one docker network per IP address and assign the containers to the correct networks.

### Additional context to this request.

There is a hacky solution [here](https://github.com/pterodactyl/panel/issues/459#issuecomment-1003668331), but since it's now possible we should add support for the official one.

### PR DESCRIPTION
**Pull request by matthewpi**
Requires https://github.com/pterodactyl/wings/pull/135

Closes #3841

### CODE REVIEW

**Comment by parkervcp** [comment]
I feel like having your traffic use the expected ip is the only way to go here and not making it an option.

**Comment by matthewpi** [comment]
> I feel like having your traffic use the expected ip is the only way to go here and not making it an option.

The problem is you lose internal container networking when this feature is enabled.  The way the feature works is best described by the Wings PR; it creates a dedicated network per-server with the `host_ipv4` option, which is the only way setting the correct outgoing IP seems to work (at least when using Docker).  I previously explored having both a dedicated network for outgoing traffic and one for internal traffic, but it is either not currently possible or requires a very specific configuration in order to work correctly.

**Comment by parkervcp** [comment]
Okay. So it's a double edged sword. On one hand you get the outbound correct. On the other you lose internal networking.

A good callout.

**Comment by Synkstar** [comment]
The only thing about this is I wish pterodactyl had an option to allow the servers to bind on the public ip but without any sort of natting or having to use host networking( since this has security issues ) so you dont get the issue where on source engine servers it can show players ips as 172.19.0.1 for example( this occurs when people join the server right after its restarted or crashed ). Plus not having natting will result in better performance.

I could probably do this with netns-dockergen but using that breaks the network usage graphs. Since I used this to have it go over a tunnel before from the container.

**Pull request merged**
