### PR TITLE
Added Disk to overview (issue:1547)

### PR DESCRIPTION
**Pull request by Sir3lit**
As requested, storage information has been added to the overview

https://github.com/pterodactyl/panel/issues/1547

image

### CODE REVIEW

**Comment by Sir3lit** [comment]
Yay, I did it correctly.

**Comment by StealWonders** [comment]
Won't this only show the amount of storage when the server is actually online?

**Comment by Sir3lit** [comment]
Yes. As the end point is only available when it's online.

**Comment by lancepioch** [comment]
The code looks fine to me as it's just all front end.
I'm pretty busy this weekend, but if somebody can test and confirm it, I think it's good to go.

**Pull request merged**
