### PR TITLE
Popout Console

### PR DESCRIPTION
**Pull request by FC-FailCoder**
I have been waiting patiently for this feature and since the last person hasn't been active for a few months, I took it in my own hands to try and remake the "<1.0" feature discussed in #2584

Things I wasn't sure about:
- The ConflictStateRenderer stops any requests going to the '/console' so I didn't know if I should make it so it can still be accessed or whatever if its a admin.
- I didn't know where to place or how to design the button. I put it on the top right. I was going to follow @mrxbox98 's design where they put it in the send command div. However, this would mean it will have to be moved or that whole div will have to be displayed with only that button in (if the user cannot send commands) which to me looks ugly.

Things included that was submitted by Dane's review ages ago:
- Used the react helper to check if the route was /console.
- Used Heroicons for the svg.
- I included a base size of 400x800 (Kinda similar to the original of the <1.0 version) and made it "truly fullscreen" allowing it to be scaled to someone's desired.
- Again wasn't sure what exactly Dane was referring to with the "This code is incorrect, you've disabled all of the features such that a popped out console won't correctly alert the user to issues." I didn't know if this meant the issues as in EULA (and other features) not being enabled or if the server is being installed.

Preview:

No console permissions (No sending commands):
image
image

Popout:
image

Normal user:
image
image

Popout:
image

Feature displays:
image
(I only tried the Minecraft one)

I want to say thank you to @mrxbox98 for their contributions.

If you are like TLDR; basically "finished" mrxbox98's feature and included most of the reviews (again wasn't sure on the last one) Dane gave.

Sorry for my bad english 🙂

### CODE REVIEW

**Comment by FC-FailCoder** [comment]
Sorry I realised yesterday I was being stupid and didn't use git cli to get the develop from this repo. Soooo I did that so it doesn't come up with 1000 files changed lmao. Sorry for the double embed in discord.

**Comment by TekExplorer** [comment]
Why was this closed?

**Comment by FC-FailCoder** [comment]
Ooooh comment didn't send... weird. Anyways, I'm not going to be able to keep working on this, since I don't have the time. Someone will probably make a better PR anyway :))

**Comment by mrxbox98** [comment]
> Ooooh comment didn't send... weird. Anyways, I'm not going to be able to keep working on this, since I don't have the time. Someone will probably make a better PR anyway :))

If its ok with you I could use the changes you made to my PR and restart work on it

**Comment by FC-FailCoder** [comment]
> > Ooooh comment didn't send... weird. Anyways, I'm not going to be able to keep working on this, since I don't have the time. Someone will probably make a better PR anyway :))
> 
> 
> 
> If its ok with you I could use the changes you made to my PR and restart work on it

due to the recent changes made to the console file & routing, it may be easier to try and start from fresh - again feel free to use my work but it won't work at all due to these changes.

**Pull request closed without merging**
