### PR TITLE
adds join button

### PR DESCRIPTION
**Pull request by gabeoliver-bicode**
This will add a join button for users to connect to their server.

### CODE REVIEW

**Comment by gabeoliver-bicode** [comment]
I could make a new database table for steam games, have the shortid of the servers that use steam automatically get put into that table so, it will only show to servers in that table.

**Comment by gabeoliver-bicode** [comment]
Do you have any ideas @Bl4ckSpr4y

**Comment by tenten8401** [comment]
Possibly a configurable "Join URI" in the egg that allows for variables

**Comment by gabeoliver-bicode** [comment]
That is a good idea I will try and do that. Thanks @tenten8401

**Comment by tenten8401** [comment]
Also, I wanted to point out, the button shouldn't be disabled by default unless you add JS to un-disable it once it's got data from the daemon / server's online

**Comment by gabeoliver-bicode** [comment]
So what you are saying for the configurable thing is that they (the admins) should be able to set the url?

**Comment by tenten8401** [comment]
Yeah, like an egg property of some sort. That way I could set the join URI to say "steam://connect{whatever_variable}" or something sort've like how you can set the startup command.

**Comment by gabeoliver-bicode** [comment]
Yeah, that's what I thought you meant. I was just confirming, okay I will get on that.

**Comment by gabeoliver-bicode** [comment]
I think I am going to add a new page when editing an egg for like "Console Configurations" or something like that and it will route to a page similar to the startup parameters thing. Where then you can change that URL.

**Comment by DaneEveritt** [comment]
Please feel free to open a new PR when you have this in a more completed state.

**Comment by lancepioch** [comment]
It's definitely a neat option that I think should be in. Obviously the logistics with determining if it's a Steam or other online service will be tricky, but good luck!

**Comment by gabeoliver-bicode** [comment]
thanks

**Pull request closed without merging**
