### PR TITLE
Feature/dockerfile completed

### PR DESCRIPTION
**Pull request by HoverEpic**
Hi, i've found out how to complete the dockerfile branch, with most common cases setup :
 - store config if start / stop panel container
 - allow setup without redis

TODO : 
- [x] nginx
- [x] php 7.2
- [x] SSL (using already existing)
- [ ] SSL (auto setup)
- [ ] docker compose example

Waiting for your change requests.

### CODE REVIEW

**Comment by DoNotSpamPls** [comment]
You're trying to merge commits which are already there :/

**Comment by HoverEpic** [comment]
@DoNotSpamPls i think these commits are on pterodactyl:develop but not on pterodactyl:feature/dockerfile

**Comment by DoNotSpamPls** [comment]
Yes, I noticed that after writing that comment, hence why it's now deleted

**Comment by DaneEveritt** [comment]
If you're completing a branch it should be merged into and based on develop. Theres no point merging a completed feature into a staging branch for said feature. :)

**Comment by HoverEpic** [comment]
So let's rebase on develop =P, I'll do this in fiew hours.

**Comment by schrej** [comment]
As discussed in the other PullRequest we were thinking about moving away from Caddy as they are commercial only now. Even though the alpine build is completely free and not one of their paid binaries ditching it might be better. We thought about using nginx instead.
We're still open to discussion if you have reasons to stick to Caddy (apart from LetsEncrypt).

**Comment by HoverEpic** [comment]
No problem, let me some days to get a ngnix based app.

**Comment by HoverEpic** [comment]
Replacing caddy is done, now, setup in http is working, for https, existing certs have to be provided.
Should i add an automatic way to setup SSL/TLS or consider Docker users can do this alone ?

**Comment by schrej** [comment]
Our plan was to have the docker image as the "easy" way to setup the panel. Automatic SSL certs would be very nice, we can also do that later though.

**Comment by DaneEveritt** [comment]
@HoverEpic @schrej @parkervcp is this in a good to go state?

**Comment by parkervcp** [comment]
@DaneEveritt I can give it a look over later today and see what I get out of it.

**Comment by HoverEpic** [comment]
Sorry for no evolution on that feature, I'm in a no code period since 10 days (and don't know when it will end). You can test non ssl setup with examples I've provided, should work as intended.

**Comment by quikstrike** [comment]
Is this in a place where an official image could be built, or is stuff still missing from it? I'd gladly lend a hand in getting this completed to get an official image up and going.

**Comment by parkervcp** [comment]
Currently this is not complete to me due to is not being able to auto-gen ssl certs. Though I have been looking into it as well.

**Comment by quikstrike** [comment]
I'll go ahead and work on getting SSL certs generating then, unless you were already working on that @parkervcp ? Let me know.

**Comment by quikstrike** [comment]
I've completed the changes to add auto Lets Encrypt certificate creation, but I'm not sure how to proceed with pushing my changes. Should I add them to @HoverEpic existing work, or should I create my own pull request? Let me know how you would like me to proceed.

**Comment by DaneEveritt** [comment]
@quikstrike If you branched it from @HoverEpic's work you should be able to open a new PR here with your changes and it'll also pull in Hover's work as well.

**Comment by DaneEveritt** [comment]
Lets move to #1117 which extends this.

**Pull request closed without merging**
