### PR TITLE
More variables for eggs to use

### PR DESCRIPTION
**Pull request by AlvinVrolijk**
I wanted to use more {{server. variables in my egg configurations

### CODE REVIEW

**Review by AlvinVrolijk — COMMENTED** [review]
My version

**Comment by james121op** [comment]
but why do we need these new variables what is the use case

**Comment by DaneEveritt** [comment]
The only two I'm tempted to allow are name & description, unless there is a justifiable use case for the others.

**Comment by AlvinVrolijk** [comment]
@DaneEveritt It's simple.. I want to know the uuidShort from in the container to use on a API to scale Minecraft servers and have them all have a unique name. The name is so the application knows how to call the server in general (ex: int-dev-34fds4d) and the id good to have if you want to communicate back to the Pterodactyl API. External ID same for development purposes.

**Comment by DaneEveritt** [comment]
closed in 2eda1995b90fd894a40a2b2248f71d5bb89da2ce — I won't be adding other fields at this time.

**Pull request closed without merging**
