### PR TITLE
Allow daemon to be configured on privileged ports

### LINKED ISSUE #1511: Allow Daemon Port Proxying
**Is your feature request related to a problem? Please describe.**
I want to proxy pass the daemon to be on a subdomain on port 443/80, instead of exposing a random port on the daemon server. 

**Describe the solution you'd like**
Currently you can't set the listen port of the daemon and the port the panel will actually connect to different values.
Either add an option to add a port in the FQDN field in the node settings, or remove the lower bound restriction on the daemon port field (then the user would change the listen port manually in the daemon configuration).

### PR DESCRIPTION
**Pull request by tenten8401**
Closes #1511

I don't know if this is the only thing that needs to be changed or not

### CODE REVIEW

**Comment by DaneEveritt** [comment]
But, why?

**Comment by DaneEveritt** [comment]
Can't wait for people to screw this up 👍

**Comment by DaneEveritt** [comment]
Please fix this PR, you did it against master

**Comment by tenten8401** [comment]
Welp now I broke it and can't re-open it... I clearly need to learn to use git a little better.

**Pull request closed without merging**
